<a href="https://colab.research.google.com/github/bayremsyoud/Gestion-de-projets/blob/master/45.%20Day45%20KNN%20Classification(IRIS)/Day45_KNN_Classification(Iris).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                      Day45: KNN Classification (Iris)  By: Loga Aswin

In [170]:
#importing libraries
import numpy as np
import pandas as pd

**Data Pre-processing :**

In [171]:
# Importing the dataset
df = pd.read_csv('iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [172]:
df.shape

(150, 5)

In [173]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [175]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [176]:
df.species.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [177]:
df['species'] = df['species'].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})

In [178]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [179]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [192]:
df=df.merge(pd.get_dummies(df.species, prefix='species'), left_index=True, right_index=True)
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species  \
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     species_setosa_x  species_versicolor_x  species_virginica_x  \
145             False                 False                 True   
146             False                 False                 True   
147             False                 False                 True   
148             False                 False                 True   
149             False                 False                 True   

     species_setosa_y  species_versicolor_y  species_virginica_y  \
145             False                 False                 True   
146             False                 False                 True   
147             False                 False                 True   
148             False                 False                 True   
149             False                 False                 True   

     species_setosa  species_versicolor  species_virginica  
145           False               False               True  
146           False               False               True  
147           False               False               True  
148           False               False               True  
149           False               False               True

In [193]:
df.merge(right=df, how='left', left_on='species', right_on='species')

sepal_length_x  sepal_width_x  petal_length_x  petal_width_x    species  \
0                5.1            3.5             1.4            0.2     setosa   
1                5.1            3.5             1.4            0.2     setosa   
2                5.1            3.5             1.4            0.2     setosa   
3                5.1            3.5             1.4            0.2     setosa   
4                5.1            3.5             1.4            0.2     setosa   
...              ...            ...             ...            ...        ...   
7495             5.9            3.0             5.1            1.8  virginica   
7496             5.9            3.0             5.1            1.8  virginica   
7497             5.9            3.0             5.1            1.8  virginica   
7498             5.9            3.0             5.1            1.8  virginica   
7499             5.9            3.0             5.1            1.8  virginica   

      species_setosa_x_x  species_versicolor_x_x  species_virginica_x_x  \
0                   True                   False                  False   
1                   True                   False                  False   
2                   True                   False                  False   
3                   True                   False                  False   
4                   True                   False                  False   
...                  ...                     ...                    ...   
7495               False                   False                   True   
7496               False                   False                   True   
7497               False                   False                   True   
7498               False                   False                   True   
7499               False                   False                   True   

      species_setosa_y_x  species_versicolor_y_x  ...  petal_width_y  \
0                   True                   False  ...            0.2   
1                   True                   False  ...            0.2   
2                   True                   False  ...            0.2   
3                   True                   False  ...            0.2   
4                   True                   False  ...            0.2   
...                  ...                     ...  ...            ...   
7495               False                   False  ...            2.3   
7496               False                   False  ...            1.9   
7497               False                   False  ...            2.0   
7498               False                   False  ...            2.3   
7499               False                   False  ...            1.8   

      species_setosa_x_y  species_versicolor_x_y  species_virginica_x_y  \
0                   True                   False                  False   
1                   True                   False                  False   
2                   True                   False                  False   
3                   True                   False                  False   
4                   True                   False                  False   
...                  ...                     ...                    ...   
7495               False                   False                   True   
7496               False                   False                   True   
7497               False                   False                   True   
7498               False                   False                   True   
7499               False                   False                   True   

      species_setosa_y_y  species_versicolor_y_y  species_virginica_y_y  \
0                   True                   False                  False   
1                   True                   False                  False   
2                   True                   False                  False   
3                   True                   False                  

In [182]:
X = df.drop('species', axis=1)
Y = df['species']

In [183]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 40)

In [184]:
from sklearn.neighbors import KNeighborsClassifier

**Creating and Training KNN Model:**

In [185]:
knn_clf = KNeighborsClassifier(n_neighbors=5, metric='euclidean', p=2)
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean')

**Predict Test Results:**

In [186]:
y_pred = knn_clf.predict(X_test)

In [187]:
pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

Actual   Predicted
38       setosa      setosa
66   versicolor  versicolor
115   virginica   virginica
117   virginica   virginica
89   versicolor  versicolor
136   virginica   virginica
68   versicolor  versicolor
94   versicolor  versicolor
84   versicolor  versicolor
28       setosa      setosa
90   versicolor  versicolor
11       setosa      setosa
40       setosa      setosa
126   virginica   virginica
79   versicolor  versicolor
144   virginica   virginica
123   virginica   virginica
124   virginica   virginica
76   versicolor  versicolor
59   versicolor  versicolor
132   virginica   virginica
105   virginica   virginica
53   versicolor  versicolor
17       setosa      setosa
64   versicolor  versicolor
18       setosa      setosa
13       setosa      setosa
116   virginica   virginica
9        setosa      setosa
81   versicolor  versicolor

**Model Evaluation Metrics**

In [188]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

score = accuracy_score(y_test, y_pred)
print(score)

1.0


In [189]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [190]:
m1 = confusion_matrix(y_test, y_pred)
print(m1)

[[ 8  0  0]
 [ 0 12  0]
 [ 0  0 10]]
